### PR TITLE
Added support for named credentials

### PR DESCRIPTION
**Pull request by jrz**
Salesforce can handle oauth authorization and refresh.

Opted for a static factory method because of constructor clashes. It would probably be a good thing do refactor the other constructors into  withAccessToken and 3xwithClientId

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @jrz, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by jrz** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @jrz has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by AndersonKatharineTNC** [comment]
Can you please update the authentication doc: https://github.com/box/box-salesforce-sdk/blob/master/doc/authentication.md with sample code using Named Credentials with the SDK?

**Comment by rgalanakis** [comment]
Would it be possible to merge this? Or are there other ways to use Named Credentials (or some other way to avoid requests automatically trying to auth)?

**Pull request closed without merging**
