### PR TITLE
Fix compilation issues

### LINKED ISSUE #34: Issue installing
Failures:
classes/BoxApiConnection.cls(69,37):Dependent class is invalid and needs recompilation:
Class.BoxApiRequest.getBoxResourceResponseBody: line 205, column 23
BoxResource: line 36, column 36: Dependent class is invalid and needs recompilation:
BoxFolder: line 341, column 12: Invalid type: BoxFile.Info
classes/BoxApiConnectionTests.cls(11,37):Dependent class is invalid and needs recompilation:
Class.BoxApiConnection.authenticate: line 69, column 37

### PR DESCRIPTION
**Pull request by drewcparker**
Fix a few typos in BoxFile and BoxFileTests that were preventing
compilation and the 'Deploy to Salesforce' functionality.

Closes #34, #37, and #40.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @drewcparker, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by drewcparker** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @drewcparker has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by dp3000** [comment]
Closes #42

**Comment by dp3000** [comment]
Closes #40

**Pull request merged**
