### PR TITLE
Added "As-User". Simply call api.setAsUser() before calling any Box A…

### PR DESCRIPTION
**Pull request by banderson5144**
Added As-User support.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @banderson5144, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by banderson5144** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @banderson5144 has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by banderson5144** [comment]
Parsing of scientific notation

**Comment by bassman531** [comment]
Hi @banderson5144 
Sorry, I just saw this pull request.  Thanks for the contributions!

I'll go through the legwork of creating issues for these 2 commits and I'll replicate your work in pull requests.  For future reference, the contributing guidelines are [here](https://github.com/box/box-salesforce-sdk/blob/master/CONTRIBUTING.md).

**Comment by banderson5144** [comment]
No problem. I actually have to update a test class. I'll go through the
proper procedures for that.

**Pull request closed without merging**
